// 图片页面的常量

const environment = process.env.NODE_ENV;
const prefix = environment !== 'development'
    ? 'https://rew6x5abdynwrxgh.public.blob.vercel-storage.com/imgs' : '';

    export const WALLPAPER_IMAGE_LIST = [
    '/wallpaper/Wallpaper1.jpg',
    '/wallpaper/Wallpaper2.jpg',
    '/wallpaper/Wallpaper3.jpg',
    '/wallpaper/Wallpaper4.jpg',
    '/wallpaper/Wallpaper5.jpg',
    '/wallpaper/Wallpaper6.jpg',
    '/wallpaper/Wallpaper7.jpg',
    '/wallpaper/Wallpaper8.jpg',
    '/wallpaper/Wallpaper9.jpg',
    '/wallpaper/Wallpaper10.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_011.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_012.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_013.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_014.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_015.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_016.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_018.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_019.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_020.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_021.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_022.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_024.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_025.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_026.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_027.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_028.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_029.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_030.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_031.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_032.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_033.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_034.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_035.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_036.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_037.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_038.jpg',
    '/wallpaper/blackmyth_wukong_wallpaper_039.jpg'
].map((item) => `${prefix}${item}`);

export const SCREENSHOT_IMAGE_LIST = [
    '/screenshot/screenshot1.jpg',
    '/screenshot/screenshot2.jpg',
    '/screenshot/screenshot3.jpg',
    '/screenshot/screenshot4.jpg',
    '/screenshot/screenshot5.jpg',
    '/screenshot/screenshot6.jpg',
    '/screenshot/screenshot7.jpg',
    '/screenshot/screenshot8.jpg',
    '/screenshot/screenshot9.jpg',
    '/screenshot/screenshot10.jpg',
    '/screenshot/screenshot11.jpg',
    '/screenshot/screenshot12.jpg',
    '/screenshot/blackmyth_wukong_screenshot_013.jpg',
    '/screenshot/blackmyth_wukong_screenshot_014.jpg',
    '/screenshot/blackmyth_wukong_screenshot_015.jpg',
    '/screenshot/blackmyth_wukong_screenshot_016.jpg',
    '/screenshot/blackmyth_wukong_screenshot_017.jpg',
    '/screenshot/blackmyth_wukong_screenshot_018.jpg',
    '/screenshot/blackmyth_wukong_screenshot_019.jpg',
    '/screenshot/blackmyth_wukong_screenshot_020.jpg',
    '/screenshot/blackmyth_wukong_screenshot_021.jpg',
    '/screenshot/blackmyth_wukong_screenshot_022.jpg',
    '/screenshot/blackmyth_wukong_screenshot_023.jpg',
    '/screenshot/blackmyth_wukong_screenshot_024.jpg',
    '/screenshot/blackmyth_wukong_screenshot_025.jpg',
    '/screenshot/blackmyth_wukong_screenshot_026.jpg',
    '/screenshot/blackmyth_wukong_screenshot_027.jpg',
    '/screenshot/blackmyth_wukong_screenshot_028.jpg',
    '/screenshot/blackmyth_wukong_screenshot_029.jpg',
    '/screenshot/blackmyth_wukong_screenshot_030.jpg',
    '/screenshot/blackmyth_wukong_screenshot_031.jpg',
    '/screenshot/blackmyth_wukong_screenshot_032.jpg'
].map((item) => `${prefix}${item}`);

export const CONCEPT_IMAGE_LIST = [
    '/concept/blackmyth_wukong_concept_06.jpg',
    '/concept/blackmyth_wukong_concept_07.jpg',
    '/concept/blackmyth_wukong_concept_08.jpg',
    '/concept/blackmyth_wukong_concept_09.jpg',
    '/concept/blackmyth_wukong_concept_c_02.jpg',
    '/concept/blackmyth_wukong_concept_c_03.jpg',
    '/concept/blackmyth_wukong_concept_c_04.jpg',
    '/concept/blackmyth_wukong_concept_c_05.jpg',
    '/concept/blackmyth_wukong_concept_c_06.jpg',
    '/concept/blackmyth_wukong_concept_c_07.jpg',
    '/concept/blackmyth_wukong_concept_c_08.jpg',
    '/concept/blackmyth_wukong_concept_c_09.jpg',
    '/concept/Concept_guishiwei.jpg',
    '/concept/Concept_heifenshan1.jpg',
    '/concept/Concept_heifenshan2.jpg',
    '/concept/Concept_heifenshan3.jpg',
    '/concept/Concept_heifenshan4.jpg',
    '/concept/Concept_huodaolang.jpg',
    '/concept/Concept_landscape1.jpg',
    '/concept/Concept_landscape2.jpg',
    '/concept/Concept_landscape3.jpg',
    '/concept/Concept_landscape6.jpg',
    '/concept/Concept_langren.jpg',
    '/concept/Concept_lingxudaozhang.jpg',
    '/concept/Concept_tudi.jpg',
    '/concept/Concept_wukong.jpg'
].map((item) => `${prefix}${item}`);
